import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Nil To Zero</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

         <div className={styles.homeContainer}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}           
                src="https://images.unsplash.com/photo-1559047838-d2ceb47b6ce9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGRlcHRoJTIwZWZmZWN0fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=700&q=60"
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"   
                priority={true}             
            />  
    
            <h1 className={`${styles['']} ${styles['home__h1']}`}>NIL TO ZERO</h1>          
            <h1 className={`${styles['textCenter']} ${styles['home__h1b']}`}>Web app design agency</h1> 
               <p className={`${styles['textCenter']} ${styles['home__p']}`}>
                 Its time to bring your idea to life
               </p>           
       </div>   

    <div className={styles.gridContainer}>
      <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}     
                src="https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8d2ViJTIwZGVzaWdufGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=700&q=60"            
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>WEB DESIGN</h1>    
        </div>
 
      <div className={styles.container}>
        <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}
                src="https://images.unsplash.com/photo-1535303311164-664fc9ec6532?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8c29jaWFsJTIwbWVkaWF8ZW58MHx8MHx8&auto=format&fit=crop&w=700&q=60"             
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>DEVELOPMENT</h1>    
        </div>      

        <div className={styles.container}>
        <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}
                src="https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c29jaWFsJTIwbWVkaWF8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60"              
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>SOCIAL MEDIA</h1>    
        </div>  

      <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}   
                src="https://images.unsplash.com/photo-1511296265581-c2450046447d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTh8fHNlb3xlbnwwfHwwfHw%3D&auto=format&fit=crop&w=500&q=60"             
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h1 className={styles.landingText}>SEO</h1>    
       </div>              
     </div>
  
     <div className={`${styles['homeContainer']} ${styles['mt1']}`}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}     
                src="https://images.unsplash.com/photo-1599689444589-133726281155?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8d2h5JTIwd2FpdHxlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60" 
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"                
            />            
            <h1 className={`${styles['textCenter']} ${styles['home__h1']}`}>Why wait ?</h1>          
            <h1 className={`${styles['textCenter']} ${styles['home__h1b']}`}>Sole Trader, Limited, Start Up Etc</h1>           
            <p className={`${styles['textCenter']} ${styles['home__p']}`}>LETS GET STARTED</p>                      
    </div>

    <div className={styles.secTwo}>
       <p>We are offering a limited number of FREE web development offers.
        So if your struggling during the cost of living crisis maybe now is the time to launch your idea
        </p>
    </div>

    <div className={styles.gridContainer}>
        <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}               
                src="https://images.unsplash.com/photo-1497215728101-856f4ea42174?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8b2ZmaWNlJTIwcGxhbnRzfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=700&q=60" 
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>FREE <br/> Project</h3>
            <h3 className={styles.landingText2}>SINGLE PAGE APP</h3>   
            <h3 className={styles.landingText2}>SET TEMPLATE</h3>     
       </div>

      <div className={styles.container}>
        <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}
                src="https://images.unsplash.com/photo-1483058712412-4245e9b90334?ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjV8fG9mZmljZSUyMHBsYW50c3xlbnwwfHwwfHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60"              
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>Pay monthly<br/>Project</h3>    
            <h3 className={styles.landingText2}>Break the cost down</h3>   
            <h3 className={styles.landingText2}>Monthly</h3> 
        </div>      

      <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}      
                src="https://images.unsplash.com/photo-1587290494402-1bdfbd34930f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MXwxMTUyNDgyN3x8ZW58MHx8fHw%3D&auto=format&fit=crop&w=500&q=60"              
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>BETA<br/>Project</h3>
            <h3 className={styles.landingText2}>SPA + UPDATES</h3>   
            <h3 className={styles.landingText2}>WORTH £2000<br/>ONLY £200 </h3>     
       </div>      

       <div className={styles.container}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}                
                src="https://images.unsplash.com/photo-1526178613552-2b45c6c302f0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8c2hvcHBpbmclMjBjYXJ0JTIwd2VifGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60"               
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"
            />    
            <h3 className={styles.landingText2}>Social Media<br/> Project</h3> 
            <h3 className={styles.landingText2}>SET UP SUPPORT</h3>   
            <h3 className={styles.landingText2}>BUSINESS ADVICE</h3> 
       </div>          
    </div>      

    <div className={`${styles['homeContainer']} ${styles['mt1']}`}>
         <div className={styles.gradientOverlay}></div>
            <Image
                className={styles.landingImage}          
                src="https://images.unsplash.com/photo-1497282003564-004631e01464?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8ZGVwdGh8ZW58MHx8MHx8&auto=format&fit=crop&w=700&q=60"
                layout='fill'
                objectFit='cover'
                objectPosition='center'
                alt="logo"                
            /> 
              <h1 className={`${styles['textCenter']} ${styles['home__h1']}`}>NIL TO ZERO</h1>                     
              <h1 className={`${styles['textCenter']} ${styles['home__h1b']}`}>ARE YOU READY FOR A CHANGE</h1> 
              <p className={`${styles['textCenter']} ${styles['home__p']}`}>
                LETS GET STARTED
              </p>            
    </div>        

    <footer className={`${styles['footer__container']} ${styles['']}`}>
		
			<div className={styles.footercol}>
				<ul className={styles.footercol__ul__list}>
		  		<li>Nil to Zero</li>
			  	{/*  */}
        	<li><span className='material-icons'>markunread</span> niltozero@gmail.com</li>
				</ul>
			</div>		
    
		<div className={`${styles['']} ${styles['textCenter']} ${styles['footer__copyright']}`}>
			<p>&copy; 2022 Nil to Zero</p>
		</div>

	</footer>

</div>
  )
}